apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: apps
  labels:
    app: helloworld
spec:
  replicas: 3
  selector:
   matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: fribergjspr/kubernetes:latest
          imagePullPolicy: IfNotPresent